/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface NewToDo {
    title?: string;
    contents?: string;
    priority?: Priority;
    completionDate?: Date;
}

export enum Priority {
    Low = 0,
    Medium = 1,
    High = 2
}

export interface ToDo {
    id?: number | string;
    title?: string;
    contents?: string;
    priority?: Priority;
    completionDate?: Date;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
