/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for ToDo controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, ToDo, NewToDo, ToDoId } from "../models";

@Injectable({ providedIn: "root" })
export class ToDoService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    toDoItemsGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<ToDo>>;
    toDoItemsGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<ToDo>>>;
    toDoItemsGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<ToDo>>>;
    toDoItemsGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/ToDoItems`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    toDoItemsPost(newToDo: NewToDo, observe?: 'body', options?: RequestOptions<'json'>): Observable<ToDoId>;
    toDoItemsPost(newToDo: NewToDo, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ToDoId>>;
    toDoItemsPost(newToDo: NewToDo, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ToDoId>>;
    toDoItemsPost(newToDo: NewToDo, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/ToDoItems`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, newToDo, requestOptions);
    }

    toDoItemsToDoIdDelete(toDoId: number | string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    toDoItemsToDoIdDelete(toDoId: number | string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    toDoItemsToDoIdDelete(toDoId: number | string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    toDoItemsToDoIdDelete(toDoId: number | string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/ToDoItems/${toDoId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
